### ISSUE TITLE
certificate was issued by an authority that is not trusted 

### ISSUE THREAD

**Issue by vjcitn** [ccb-hms/HarvardInovalonUserGuide#6]
Cannot connect to CCBWSQLP01 ... Database Engine server type, Server name as given (CCBWSQLP01) or localhost, Authentication Windows Authentication.   In details error number is -2146893019

**Comment by nathan-palmer** [comment]
Did you make sure to include the following step before attempting to connect?

Click Options >>, then on the Connection Properties tab. Check the Encrypt connection and Trust server certificate options if they are not already enabled.

**Comment by vjcitn** [comment]
Thank you -- missed that, now I am in.
